version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: camerapedia_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: camerapedia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: