version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: camerapedia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data using a named volume

volumes:
  postgres_data: {} # Define the named volume
